#!/bin/sh
## read system info
read -r host < /proc/sys/kernel/hostname

## os
for os in /etc/os-release /usr/lib/os-release; do
	[ -f $os ] && . $os && break
done

## wm
wm=$XDG_CURRENT_DESKTOP
[ "$wm" ] || wm=$DESKTOP_SESSION

## kernel	
	read -r _ _ version _ < /proc/version
	ke=${version%%-*}
	
# colors and palette method stolen from dylanaraps pfetch
# https://github.com/dylanaraps/pfetch
c0='[0m';
c1='[31m'; c2='[32m'
c3='[33m'; c4='[34m'
c5='[35m'; c6='[36m'
c7='[37m'; c8='[38m'
palette="[7m$c1 $c1 $c2 $c2 $c3 $c3 $c4 $c4 $c5 $c5 $c6 $c6 [m"

## output
printf '%s\n' "

    ${c5}     .-.         ${USER}${c0}@${c5}${host}
    ${c5}  __/   (        ${c6}os${c0} ~ endeavouros
    ${c5}, '-.____\\       ${c6}sh${c0} ~ ${SHELL##*/}
    ${c5} u=='/  \\        ${c6}wm${c0} ~ ${wm}
    ${c5}    /_/  \\       ${c6}kr${c0} ~ ${ke}
    ${c5}  .-''   |       
    ${c5} (  ${c5}____${c5}/${c5}_____ ${c0}  ${palette}
    
"
