.\" Manpage for jfetch. 
.TH man 9 "December 2020" "jfetch man page" "User Commands" 
.SH NAME 
jfetch \- A minimal Linux fetch script 
.SH SYNOPSIS 
jfetch 
.SH DESCRIPTION 
jfetch is a bash script which displays information about your system. 
.SH OPTIONS 
user = ${USER}
host = ${host}
distro = ${PRETTY_NAME}
wm = ${wm}
terminal = ${term}
shell = ${SHELL##*/}
kernel = ${ke}
package manager = ${manager}
packages count = ${packages}
cpu = ${cpu}
ram = ${mem}
uptime = ${up}
palette = ${palette}
display protocol = ${displayprot}
resolution = ${resolution}
model = ${model}
.SH "REPORTING BUGS" 
Report bugs to https://github.com/Jimmysit0/jfetch/issues 
